name: pull-request
on:
  pull_request: 
    types: [opened, synchronize, edited]
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/setup-node

  gitmoji:
    name: Ensure that title has a gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/gitmoji
          
  linting:
    name: Run linting
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3
      - run: yarn lint
  
  build:
    name: Run build
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3
      - run: yarn build
